### ISSUE TITLE
A hidden slider causes a failure to calculate the handle position

### ISSUE THREAD

**Issue by moreaumc** [PredixDev/px-slider#1]
When the slider is hidden, such as when it's placed within a modal, the slider position is not calculated correctly, and is set to a negative value. This is due to the fact that the _translateValueToPosition function uses the slider container's offsetWidth attribute, which is 0 when an element isn't shown.

Line 294 in the current code: 
var cW = this.$.sliderContainer.offsetWidth - cO;

**Comment by nonmetalhail** [comment]
Merged #3 which solves this issue in v0.3.0
