### ISSUE TITLE
Slider bar not moving with multiple predix Px-component on page.

### ISSUE THREAD

**Issue by VikasBisht** [PredixDev/px-slider#11]
Hi Team,

I am using 10 px-Slider along with px-datetime-range-panel,px-context-browser and px-rangepicker.

In my preview the Px-slider bars are not moving at all.

But it was working fine if there are only sliders and no other px-component,

Please can you check and help me with my query.

Regards,
vikas

**Comment by mdwragg** [comment]
Hi, can you resubmit this issue following the template?

For an issue such as this the codepen/snippet/demo is especially important. If we can't recreate it we can't fix it. 

Thanks for understanding.

**Comment by trackleaf** [comment]
I was able to reproduce this when I had a wrapper div over the px-sliders that had a hidden attribute

<div hidden$='[[someProperty]]'>
   <px-slider min="someMin" max="someMax" start-value="startMin" end-value="endMax"></px-slider>
</div>

to get around this I used the <template is="dom-if" if="[[ someProperty ]]"> instead
