### ISSUE TITLE
Can the slider styles be overriden?

### ISSUE THREAD

**Issue by chinmainpadalkar** [PredixDev/px-slider#12]
## Expected behavior and actual behavior:
I am planning to use px-slider in our application. Tried using the slider which shows the range (option2). I wanted to customize the multiHandleSVG sass property which shows the arrows indicating the min and max value as I want both the min and max value to have the arrows in the same direction(like the min one). Is it possible to override this property? The reason being, I want to use this as a slider for another component which will be built right above this slider.

Thanks.

**Comment by nonmetalhail** [comment]
Sorry, it is not currently possible to change the direction of the handles.

**Comment by chinmainpadalkar** [comment]
Ok. Thank you.
