### ISSUE TITLE
Slider does not work properly when step is set to .01

### ISSUE THREAD

**Issue by trackleaf** [PredixDev/px-slider#13]
when setting the step to the px-slider to something like .01 the handles don't work properly. They are sometimes together somewhere along the range and when you drag either of them there are sometimes where it snaps to the opposite handle even if you are dragging in the opposite direction.

Example Code:

http://codepen.io/anon/pen/BpqamL?&editors=1001

Screen Shot:
![screen shot 2017-02-08 at 1 25 07 pm](https://cloud.githubusercontent.com/assets/195582/22758156/557729cc-ee02-11e6-855c-c83dbfbd59da.png)

**Comment by nonmetalhail** [comment]
This appears to be resolved after the slider major release. Your codepen no longer works due to breaking changes, but dropping it into a functional codepen and updating the properties, I do not see the issue.
