### ISSUE TITLE
IE11: Disabled attribute is not supported in IE11.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-slider#16]
## Expected behavior and actual behavior:

A disabled slider is supported across all browsers, except IE11.  See the screenshots below from IE11 vs. Chrome.
Notice how the slider width is shrunken down making it unreadable but it does seem to be disabled.  

There are no errors in the console log.

## Steps to reproduce the problem:

See Code Snippet and view in IE11.

## Environment:

Slider version: 1.0.3
Browser: IE11

### **IE11:**
<img width="1200" alt="screen shot 2017-04-12 at 12 50 25 pm" src="https://cloud.githubusercontent.com/assets/10835611/24976542/bf05524e-1f7e-11e7-81c1-adae715727fc.png">

### **Chrome:**

![screen shot 2017-04-12 at 12 56 57 pm](https://cloud.githubusercontent.com/assets/10835611/24976770/9f50ad08-1f7f-11e7-93b6-80cb64adc698.png)

## Code Snippet:

```
<px-slider
        id="sliderMulti5"
        value="10"
        end-value="150"
        min="-20"
        max="160"
        is-range
        show-labels
        max-label-position="top"
        min-label-position="bottom"
        disabled
        hide-inputs
      >
      </px-slider>
```

**Comment by randyaskin** [comment]
Works fine in latest version.
