### ISSUE TITLE
Slider's handle should not overlay labels.

### ISSUE THREAD

**Issue by ppeyro** [PredixDev/px-slider#22]
## Expected behavior and actual behavior:

Currently if you have labels placed on the slider (top or bottom), the handle can overlay the label depending on its position.  Checked with the design team, their direction is to have the label visible no matter where the handle is placed, which potentially means increasing the height of the component and placing the label under (or above the handle).

## Environment:
Slider Version 1.0.3
Browsers: All

## Screenshots:

![screen shot 2017-04-13 at 9 55 42 am](https://cloud.githubusercontent.com/assets/10835611/25015354/493666d6-2030-11e7-955e-ee0025350690.png)

![screen shot 2017-04-13 at 9 55 30 am](https://cloud.githubusercontent.com/assets/10835611/25015362/4de55bf6-2030-11e7-959a-4c280a60ffee.png)

## Code Snippet:
```
  <px-slider
        id="sliderMulti8"
        value="0"
        end-value="200"
        min="0"
        max="250"
        is-range
        step="50"
        show-labels
        max-label-position="top"
        min-label-position="bottom"
      >
      </px-slider>

```

**Comment by nonmetalhail** [comment]
No, the label position is dev set specifically for this reason. The developer can decide what they want to happen.
