### ISSUE TITLE
Infinite Loop for endValue

### ISSUE THREAD

**Issue by trackleaf** [PredixDev/px-slider#26]
We are noticing that there is an infinite loop in method _validateValue where it calls this.set(thisVal, v) (thisVal = "endValue", v = 0....for example) before it returns valid true or false. The _endValueChanged method is listening for changes to "endValue" and it calls the _validateValue method that creates the loop. 

"Uncaught RangeError: Maximum call stack size exceeded"

hopefully this makes sense

**Comment by nonmetalhail** [comment]
Can you give exact steps to reproduce?
