### ISSUE TITLE
latest version 2.2.0 breaking our build during distribution

### ISSUE THREAD

**Issue by priyabrat1801** [PredixDev/px-slider#28]
The latest version of px-slider 2.2.0 is causing our build to fail with the below error:

undefined:1625
    throw new JS_Parse_Error(message, filename, line, col, pos);
    ^
SyntaxError: Unexpected token: punc (()
    at JS_Parse_Error.get (<anonymous>:86:23)

Downgrading to 2.1.0 does not cause the error and the build goes through successfully.

**Comment by nonmetalhail** [comment]
Slider is an ES6 component and it is probably due to that. Please see:
[https://www.predix-ui.com/#/develop/transpile](https://www.predix-ui.com/#/develop/transpile)
