### ISSUE TITLE
Feature Request: Non-linear Scales specifically logarithmic

### ISSUE THREAD

**Issue by mvelez** [PredixDev/px-slider#9]
## Expected behavior and actual behavior:
For representing data which has a large range it is more user friendly to utilize a logarithmic scale to represent the exponential growth certain data exhibits.  Classic examples of this are the Ph scale, Richter scale, and decibel scale.  My use case is health care costs which unfortunately also seem to operate over a wide range like this.

Expected would be that you can set `min` and `max` like normal but set a `scale` attribute with a scale like ln or log10 which then compensates for the scale so that the value can be used directly in calculations.

**Comment by randyaskin** [comment]
Added in v0.8.1.
